# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# set working directory
WORKDIR /app

# Install mcpo and uv for running the proxy
RUN pip install mcpo uv

# Copy your local project files into the image
COPY ./src /app/src
COPY ./pyproject.toml /app/pyproject.toml
COPY ./uv.lock /app/uv.lock
COPY README.md /app/README.md

# Install your chroma-mcp server and ALL its dependencies from local files.
# This makes your custom version available system-wide in the container.
RUN uv pip install --system .

# Use a shell entrypoint to allow dynamic port assignment via MCPO_PORT
ENTRYPOINT ["/bin/sh", "-c"]

# Call mcpo directly. It runs the chroma-mcp server using the system's python
# where both packages are installed.
CMD ["mcpo --host 0.0.0.0 --port ${MCPO_PORT:-8011} -- python -m chroma_mcp.server"]
